# Generated by Django 4.2.30 on 2026-07-09 18:05

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ai_insights',
            field=models.JSONField(blank=True, default=contacts.models.default_ai_insights),
        ),
    ]
