# Generated by Django 4.2.30 on 2026-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_ai_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_ai_deal_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
