# Generated by Django 4.2.30 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_telegram_webhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramwebhooklog',
            name='failed_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='telegramwebhooklog',
            name='processing_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
