# Generated by Django 4.2.30 on 2026-07-18 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEmailDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_hash', models.CharField(db_index=True, max_length=64)),
                ('purpose', models.CharField(choices=[('registration', 'Подтверждение регистрации'), ('password_reset', 'Восстановление пароля')], max_length=32)),
                ('encrypted_payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'db_table': 'auth_email_deliveries',
                'ordering': ('next_attempt_at', 'created_at'),
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='auth_email_queue_idx'), models.Index(fields=['recipient_hash', 'purpose', 'status'], name='auth_email_recipient_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_identifier', models.UUIDField(blank=True, db_index=True, null=True)),
                ('email_hash', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('registration_requested', 'Запрос регистрации'), ('registration_confirmed', 'Регистрация подтверждена'), ('login', 'Вход'), ('password_reset_requested', 'Запрос восстановления пароля'), ('password_reset_code_confirmed', 'Код восстановления подтверждён'), ('password_reset_completed', 'Пароль восстановлен')], db_index=True, max_length=40)),
                ('successful', models.BooleanField(db_index=True, default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_audit_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'successful', '-created_at'], name='auth_audit_action_idx'), models.Index(fields=['email_hash', '-created_at'], name='auth_audit_email_idx')],
            },
        ),
    ]
