# Generated by Django 4.2.30 on 2026-07-03

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0004_telegram_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=0)),
                ('instruction', models.TextField(blank=True, default='')),
                ('autopilot_enabled', models.BooleanField(default=False)),
                ('autopilot_mode', models.CharField(choices=[('always', 'Всегда'), ('fallback', 'Если менеджер не ответил')], default='fallback', max_length=16)),
                ('autopilot_delay', models.PositiveSmallIntegerField(default=5)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Настройки AI',
                'verbose_name_plural': 'Настройки AI',
                'db_table': 'ai_settings',
            },
        ),
        migrations.CreateModel(
            name='AIUsageDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('deals_created', models.PositiveIntegerField(default=0)),
                ('tasks_created', models.PositiveIntegerField(default=0)),
                ('contacts_updated', models.PositiveIntegerField(default=0)),
                ('autopilot_replies', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_daily_usage', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_usage_daily',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_identifier', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('instruction_updated', 'Изменение инструкции'), ('autopilot_enabled', 'Включение автопилота'), ('autopilot_disabled', 'Выключение автопилота'), ('autopilot_updated', 'Изменение автопилота')], max_length=32)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_logs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_audit_log',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='aiusagedaily',
            constraint=models.UniqueConstraint(fields=('workspace', 'date'), name='unique_ai_usage_workspace_date'),
        ),
    ]
