# Generated by Django 4.2.30 on 2026-07-03 12:58

import ai_assistant.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_telegram_webhook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiauditlog',
            name='action',
            field=models.CharField(choices=[('instruction_updated', 'Изменение инструкции'), ('autopilot_enabled', 'Включение автопилота'), ('autopilot_disabled', 'Выключение автопилота'), ('autopilot_updated', 'Изменение автопилота'), ('document_uploaded', 'Загрузка документа'), ('document_deleted', 'Удаление документа'), ('document_retry', 'Повторная обработка документа')], max_length=32),
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by_identifier', models.UUIDField(db_index=True)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=ai_assistant.models.knowledge_document_upload_to)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=128)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Обработка'), ('ready', 'Готов'), ('failed', 'Ошибка')], db_index=True, default='processing', max_length=16)),
                ('error_reason', models.TextField(blank=True, default='')),
                ('processing_attempts', models.PositiveSmallIntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_knowledge_documents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_knowledge_document',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField()),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_assistant.knowledgedocument')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_knowledge_chunk',
                'ordering': ('position',),
            },
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['workspace', 'is_deleted', 'status'], name='ai_doc_workspace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['workspace', 'is_deleted', '-created_at'], name='ai_doc_workspace_date_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['workspace', 'document'], name='ai_chunk_ws_doc_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='unique_knowledge_document_chunk_position'),
        ),
    ]
