# Generated by Django 4.2.30 on 2026-07-03 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0004_telegram_webhook'),
        ('ai_assistant', '0002_alter_aiauditlog_action_knowledgedocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта')], db_index=True, default='open', max_length=16)),
                ('context_page', models.CharField(blank=True, choices=[('dashboard', 'Рабочий стол'), ('deals', 'Сделки'), ('contacts', 'Контакты'), ('tasks', 'Задачи'), ('chat', 'Чат'), ('reports', 'Отчёты'), ('settings', 'Настройки')], default='', max_length=16)),
                ('context_entity_id', models.UUIDField(blank=True, null=True)),
                ('default_model_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_chat_sessions',
                'ordering': ('-last_activity_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'AI')], max_length=16)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Формируется'), ('streaming', 'Потоковая генерация'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('timeout', 'Таймаут'), ('cancelled', 'Отменено')], db_index=True, max_length=16)),
                ('client_message_id', models.UUIDField(blank=True, null=True)),
                ('retry_token', models.UUIDField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='ai_assistant.aichatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aichatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_messages', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['workspace', 'user', '-created_at'], name='ai_sess_ws_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['session', '-created_at', '-id'], name='ai_msg_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['workspace', 'user', '-created_at', '-id'], name='ai_msg_ws_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='aichatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('workspace', 'user', 'client_message_id'), name='unique_ai_chat_client_msg'),
        ),
        migrations.AddConstraint(
            model_name='aichatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('retry_token__isnull', False)), fields=('workspace', 'user', 'retry_token'), name='unique_ai_chat_retry_token'),
        ),
    ]
