# Generated by Django 4.2.30 on 2026-07-09 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_telegram_webhook'),
        ('messaging', '0002_outgoing_delivery'),
        ('ai_assistant', '0003_aichatsession_aichatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutomationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(default='chat_message_received', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Обработано'), ('failed', 'Ошибка'), ('ignored', 'Пропущено')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failure_type', models.CharField(blank=True, choices=[('technical', 'Техническая ошибка'), ('business', 'Бизнес-ошибка')], default='', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_automation_events', to='messaging.chat')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_automation_event', to='messaging.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_automation_events', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_automation_event',
                'ordering': ('available_at', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AIChatInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('sentiment', models.CharField(blank=True, default='', max_length=32)),
                ('objections', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='messaging.chat')),
                ('source_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='messaging.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_insights', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_chat_insights',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AIProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('contact_enrichment', 'Обогащение контакта'), ('deal_create', 'Создание сделки'), ('deal_enrichment', 'Обогащение сделки'), ('task_create', 'Создание задачи'), ('insight', 'Инсайт по чату')], max_length=32)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processed_events', to='messaging.chat')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_actions', to='ai_assistant.aiautomationevent')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processed_events', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_processed_events',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['chat', 'action_type', '-created_at'], name='ai_processed_chat_action_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aiprocessedevent',
            constraint=models.UniqueConstraint(fields=('workspace', 'event', 'action_type'), name='unique_ai_processed_event_action'),
        ),
        migrations.AddIndex(
            model_name='aichatinsight',
            index=models.Index(fields=['chat', '-created_at'], name='ai_insight_chat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aiautomationevent',
            index=models.Index(fields=['workspace', 'status', 'available_at'], name='ai_auto_event_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='aiautomationevent',
            index=models.Index(fields=['chat', '-processed_at'], name='ai_auto_event_chat_done_idx'),
        ),
    ]
