# Generated by Django 4.2.30 on 2026-07-09 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_telegram_webhook'),
        ('messaging', '0003_chat_ai_autopilot_enabled'),
        ('ai_assistant', '0004_aiautomationevent_aichatinsight_aiprocessedevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprocessedevent',
            name='action_type',
            field=models.CharField(choices=[('contact_enrichment', 'Обогащение контакта'), ('deal_create', 'Создание сделки'), ('deal_enrichment', 'Обогащение сделки'), ('task_create', 'Создание задачи'), ('insight', 'Инсайт по чату'), ('autopilot_reply', 'Ответ автопилота')], max_length=32),
        ),
        migrations.CreateModel(
            name='AIAutopilotJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('always', 'Всегда'), ('fallback', 'Если менеджер не ответил')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('sent', 'Отправлено'), ('skipped', 'Пропущено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failure_type', models.CharField(blank=True, choices=[('technical', 'Техническая ошибка'), ('business', 'Бизнес-ошибка')], default='', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('batched_message_ids', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_autopilot_jobs', to='messaging.chat')),
                ('reply_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_autopilot_reply_job', to='messaging.message')),
                ('trigger_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_autopilot_job', to='messaging.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_autopilot_jobs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_autopilot_job',
                'ordering': ('available_at', 'created_at', 'id'),
                'indexes': [models.Index(fields=['workspace', 'status', 'available_at'], name='ai_autopilot_queue_idx'), models.Index(fields=['chat', 'status', 'available_at'], name='ai_autopilot_chat_idx'), models.Index(fields=['chat', '-processed_at'], name='ai_autopilot_done_idx')],
            },
        ),
    ]
