# Generated by Django 4.2.30 on 2026-07-09 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_telegram_webhook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_chat_ai_autopilot_enabled'),
        ('ai_assistant', '0005_alter_aiprocessedevent_action_type_aiautopilotjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutomationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ai_contact_created', 'AI создал контакт'), ('ai_deal_created', 'AI создал сделку'), ('ai_task_created', 'AI создал задачу'), ('ai_contact_updated', 'AI обновил контакт'), ('ai_deal_updated', 'AI обновил сделку'), ('ai_insights_extracted', 'AI извлёк инсайты'), ('ai_autopilot_sent', 'Автопилот отправил ответ'), ('ai_decision_skipped', 'AI пропустил действие'), ('ai_limit_reached', 'AI достиг лимита'), ('ai_action_failed', 'AI-действие завершилось ошибкой')], db_index=True, max_length=32)),
                ('action_type', models.CharField(db_index=True, max_length=32)),
                ('trigger', models.CharField(blank=True, default='', max_length=64)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('raw_message', models.TextField(blank=True, default='')),
                ('ai_prompt', models.TextField(blank=True, default='')),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to='messaging.chat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to='messaging.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_automation_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_automation_audit_logs', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'ai_automation_audit_log',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['workspace', '-created_at', '-id'], name='ai_auto_audit_ws_created_idx'), models.Index(fields=['workspace', 'action_type', '-created_at'], name='ai_auto_audit_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='aiautomationauditlog',
            constraint=models.UniqueConstraint(fields=('workspace', 'correlation_id', 'action_type'), name='unique_ai_auto_audit_action'),
        ),
    ]
