# Generated by Django 4.2.30 on 2026-07-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_aiautomationauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiautomationauditlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiautomationauditlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
