# Generated by Django 4.2.30 on 2026-07-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_outgoing_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ai_autopilot_enabled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
