# Generated by Django 4.2.30 on 2026-07-13 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0004_telegram_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deal_created', 'Новая сделка'), ('deal_updated', 'Изменение сделки'), ('deal_attention', 'Сделка требует внимания'), ('ai_contact_created', 'AI создал контакт'), ('ai_contact_updated', 'AI обновил контакт'), ('task_due_soon', 'Приближается срок задачи'), ('task_overdue', 'Задача просрочена'), ('chat_new_message', 'Новое сообщение клиента'), ('chat_returned', 'Клиент вернулся'), ('chat_missed_message', 'Пропущено сообщение клиента'), ('ai_deal_created', 'AI создал сделку'), ('ai_task_created', 'AI создал задачу'), ('ai_insight_extracted', 'AI нашёл важную информацию'), ('ai_action_failed', 'Ошибка AI-действия')], db_index=True, max_length=64)),
                ('title', models.CharField(max_length=60)),
                ('content', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=36)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'is_deleted', 'is_read'], name='notif_user_read_idx'), models.Index(fields=['user', 'is_deleted', '-created_at', '-id'], name='notif_user_created_idx'), models.Index(fields=['workspace', 'type', '-created_at'], name='notif_ws_type_created_idx')],
            },
        ),
    ]
