# Generated by Django 4.2.30 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(
                choices=[
                    ('deal_created', 'Новая сделка'),
                    ('deal_updated', 'Изменение сделки'),
                    ('deal_attention', 'Сделка требует внимания'),
                    ('ai_contact_created', 'AI создал контакт'),
                    ('ai_contact_updated', 'AI обновил контакт'),
                    ('ai_deal_updated', 'AI обновил сделку'),
                    ('task_due_soon', 'Приближается срок задачи'),
                    ('task_overdue', 'Задача просрочена'),
                    ('chat_new_message', 'Новое сообщение клиента'),
                    ('chat_returned', 'Клиент вернулся'),
                    ('chat_missed_message', 'Пропущено сообщение клиента'),
                    (
                        'chat_message_delivery_failed',
                        'Ошибка доставки сообщения',
                    ),
                    ('ai_deal_created', 'AI создал сделку'),
                    ('ai_task_created', 'AI создал задачу'),
                    ('ai_insight_extracted', 'AI нашёл важную информацию'),
                    ('ai_autopilot_sent', 'Автопилот отправил ответ'),
                    ('ai_limit_reached', 'AI достиг лимита'),
                    ('ai_action_failed', 'Ошибка AI-действия'),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
